apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    app: app1
spec:
  containers:
  - image: balchua/app1:1.0 
    #command: ["docker-entrypoint.sh"]
    args: ['/usr/src/app/main-good.sh']
    imagePullPolicy: IfNotPresent
    name:  app1
  securityContext:
    runAsUser: 2000
    fsGroup: 2000
  restartPolicy: Never
